export const friendsActionType = {
  DO_GET_FRIEND: 'DO_GET_FRIEND',
  SAVE_FRIEND_LIST: 'SAVE_FRIEND_LIST',
  DO_ADD_FRIEND: 'DO_ADD_FRIEND',
  ADDED_FRIEND_LIST: 'ADDED_FRIEND_LIST',
  DO_ADD_FRIEND_LIST: 'DO_ADD_FRIEND_LIST',
  DO_CACHE_FRIEND: 'DO_CACHE_FRIEND',
  CLEAR_FRIEND: 'CLEAR_FRIEND',
};
